version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
    networks:
      - 12-factor-app

  redis:
    image: redis:7
    networks:
      - 12-factor-app

networks:
  12-factor-app:
