version: "3.8"
services:
  web:
    # image: sharmaarnav/12-factor-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - 12-factor-app
  redis:
    image: redis:7
    networks:
      - 12-factor-app

networks:
  12-factor-app:
