name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -t sharmaarnav/12-factor-app:${{ github.sha}} .

      - name: Run Tests
        run: |
          docker run --rm sharmaarnav/12-factor-app:${{ github.sha}} pytest tests/ --disable-warnings

      - name: Push Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push sharmaarnav/12-factor-app:${{ github.sha}}
